networks:
    network:
        driver: bridge

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        ports:
            - '${PORT}:${PORT}'
        environment:
            TZ: ${TZ}
            NODE_ENV: ${NODE_ENV}
            PORR: ${PORT}
        volumes:
            - .:/usr/src/app # Optional: Mount the current directory for live code update
            - /usr/src/app/node_modules # Ensure node_modules isn't overwritten
        networks:
            - network
