networks:
    network:
        driver: bridge

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        ports:
            - '3000:3000'
        environment:
            TZ: ${TZ}
            NODE_ENV: ${NODE_ENV}
        volumes:
            - .:/usr/src/app # Optional: Mount the current directory for live code updates
        networks:
            - network
        develop:
            watch:
                - action: sync
                  path: .
                  target: /usr/src/app
                  ignore:
                      - node_modules/ # Ignore files/folders like node_modules to avoid syncing them
                - action: rebuild
                  path: package.json
